### ISSUE TITLE
zsh: command not found: display_info

### ISSUE THREAD

**Issue by huanzhang** [kootenpv/whereami#27]
osx got "zsh: command not found: display_info" error

**Comment by kootenpv** [comment]
Turns out:

https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/common-aliases/common-aliases.plugin.zsh#L47

In zsh `whereami` is an alias. Try running another shell.

Or try calling by its full path:

e.g. for example: `/Library/Frameworks/Python.framework/Versions/3.5/bin/whereami`

2 ways to find it out: open another non-zsh shell and try `which whereami`.

Or open a python shell:
```

>>> import whereami
>>> whereami
<module 'whereami' from '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/whereami/__init__.py'>
```

**Comment by mcornella** [comment]
You can also run `unalias whereami` to delete the alias. We're going to delete that, FWIW. (Closable issue).

**Comment by kootenpv** [comment]
Thanks for the update and another solution @mcornella, much appreciated.
